metric: COCO
num_classes: 11

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/train.json
    dataset_dir: /Users/jiangjingjing/Desktop/dataset
    data_fields: ['info', 'images', 'annotations', 'categories']

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/valid.json
    dataset_dir: /Users/jiangjingjing/Desktop/dataset

TestDataset:
  !ImageFolder
    anno_path: annotations/valid.json
